-- Query for SANCTUARY table
SELECT * FROM SANCTUARY;

-- Query for EMPLOYEE table
SELECT * FROM EMPLOYEE;

-- Query for CARETAKER table
SELECT * FROM CARETAKER;

-- Query for SANCTUARY_STAFF table
SELECT * FROM SANCTUARY_STAFF;

-- Query for GUIDE table
SELECT * FROM GUIDE;

-- Query for COACHES table
SELECT * FROM COACHES;

-- Query for HABITAT table
SELECT * FROM HABITAT;

-- Query for FLORA table
SELECT * FROM FLORA;

-- Query for FLORA_HABITAT table
SELECT * FROM FLORA_HABITAT;

-- Query for VET table
SELECT * FROM VET;

-- Query for WILDLIFE table
SELECT * FROM WILDLIFE;

-- Query for CARNIVORE table
SELECT * FROM CARNIVORE;

-- Query for OMNIVORE table
SELECT * FROM OMNIVORE;

-- Query for HERBIVORE table
SELECT * FROM HERBIVORE;

-- Query for WILDLIFE_TRACKING table
SELECT * FROM WILDLIFE_TRACKING;

-- Query for TOURIST table
SELECT * FROM TOURIST;

-- Query for VISITS table
SELECT * FROM VISITS;

-- Query for OUTREACH_PROGRAM table
SELECT * FROM OUTREACH_PROGRAM;

-- Query for VOLUNTEER table
SELECT * FROM VOLUNTEER;

-- Query for SUPPLIER table
SELECT * FROM SUPPLIER;

-- Query for FOOD table
SELECT * FROM FOOD;

-- Query for FOOD_SUPPLY table
SELECT * FROM FOOD_SUPPLY;

-- Query for WILDLIFE_FOOD table
SELECT * FROM WILDLIFE_FOOD;

-- Query for WILDLIFE_HABITAT table
SELECT * FROM WILDLIFE_HABITAT;